#Numpy Crash course

In [1]:
import numpy as np

In [2]:
np.__version__

'1.26.4'

#creating Arrays

In [6]:
my_list = [0,1,2,3,4,5]
my_list

[0, 1, 2, 3, 4, 5]

In [7]:
type(my_list)

list

In [8]:
arr = np.array(my_list)

In [9]:
arr

array([0, 1, 2, 3, 4, 5])

In [11]:
type(arr)

numpy.ndarray

In [12]:
type(my_list)

list

In [14]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [15]:
np.arange(3.0)

array([0., 1., 2.])

In [16]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
np.arange(0,5)

array([0, 1, 2, 3, 4])

In [18]:
np.arange(10,20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [19]:
np.arange(20,10)

array([], dtype=int32)

In [20]:
np.arange(-20,10)

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,
        -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,
         6,   7,   8,   9])

In [21]:
np.arange(-16,10)

array([-16, -15, -14, -13, -12, -11, -10,  -9,  -8,  -7,  -6,  -5,  -4,
        -3,  -2,  -1,   0,   1,   2,   3,   4,   5,   6,   7,   8,   9])

In [22]:
np.arange(-20,-10)

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11])

In [23]:
np.arange(30,20) # 1st arg always be <then 2nd arg

array([], dtype=int32)

In [26]:
b = np.arange(-30,20)

In [27]:
b

array([-30, -29, -28, -27, -26, -25, -24, -23, -22, -21, -20, -19, -18,
       -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,  -7,  -6,  -5,
        -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,   6,   7,   8,
         9,  10,  11,  12,  13,  14,  15,  16,  17,  18,  19])

In [28]:
np.arange(10,10)

array([], dtype=int32)

In [29]:
np.arange(-20,20)

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,
        -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,
         6,   7,   8,   9,  10,  11,  12,  13,  14,  15,  16,  17,  18,
        19])

In [31]:
np.arange(10,30,5) # 10-starting from-end point 5- step count

array([10, 15, 20, 25])

In [32]:
np.arange(0,10,3)

array([0, 3, 6, 9])

In [33]:
np.arange(10,30,5,1)

TypeError: Cannot interpret '1' as a data type

In [35]:
b1 = np.zeros(2) #parameter tunning
b1

array([0., 0.])

In [36]:
np.zeros(5,dtype=int) # hyperparameter tuninng

array([0, 0, 0, 0, 0])

In [37]:
zero = np.zeros((2,2))
zero

array([[0., 0.],
       [0., 0.]])

In [38]:
np.zeros((10,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [39]:
np.zeros((2,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [40]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [41]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [42]:
np.zeros((10,30))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0

In [43]:
np.zeros((5,10)) #bydefault 1arge -- will give row & 2nd arg -columns

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [45]:
n = (5,7)
n1 = (6,8)
print(np.zeros(n)) # prameters tuning g
#print(np.zeros (n1,dtype=int))## hyperparameter tuning

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


In [46]:
print(np.zeros(n1))

[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]


In [47]:
np.ones(4,dtype=int)

array([1, 1, 1, 1])

In [48]:
np.ones(4)

array([1., 1., 1., 1.])

In [49]:
n

(5, 7)

In [50]:
np.ones(n)

array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]])

In [51]:
np.ones((5,4), dtype=int) # by default 5- rows & 4- columns

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [52]:
np.twos((2,3))

AttributeError: module 'numpy' has no attribute 'twos'

In [53]:
np.ones((2,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [54]:
np.ones((6,10),dtype = int)

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [55]:
np.twos((2,4))

AttributeError: module 'numpy' has no attribute 'twos'

In [56]:
np.three((2,4))

AttributeError: module 'numpy' has no attribute 'three'

#please add new notebook &compare with np*

In [61]:
from numpy impor * # internally it called 217 functionality
arange(3)

SyntaxError: invalid syntax (1800449956.py, line 1)

In [62]:
>>> from numpy import*
>>> arange(3)

array([0, 1, 2])

In [63]:
range(12)
list(range(12))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]

In [64]:
y = list(range(12))

In [65]:
y

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]

In [67]:
>>> from numpy import*
>>> zeros(5)

array([0., 0., 0., 0., 0.])

In [68]:
np.threes((3,2))

AttributeError: module 'numpy' has no attribute 'threes'

In [69]:
rand(3,2)
random.rand(3,2)

NameError: name 'rand' is not defined

In [70]:
np.random.rand(4)

array([0.58443821, 0.69712636, 0.76403689, 0.81003244])

In [71]:
np.rand(4)

AttributeError: module 'numpy' has no attribute 'rand'

In [72]:
np.random.rand(2,4)

array([[0.01592108, 0.63860057, 0.06464838, 0.6067224 ],
       [0.7882913 , 0.01138518, 0.50649163, 0.96509188]])

In [73]:
np.random.randint(2,20) #2nd argument is exusive

13

In [74]:
np.random.randint(0,2)

0

In [75]:
np.random.randint(1,10,4)

array([1, 1, 6, 5])

In [76]:
np.random.randint(1,3,5)

array([2, 2, 1, 2, 1])

In [77]:
np.random.randint(30,20,10)

ValueError: low >= high

In [78]:
np.random.randint(1)

0

In [81]:
np.random.randint(5,9)

7

In [82]:
np.random.randint(10,21,3)

array([12, 20, 16])

In [83]:
np.random.randint(1,12,10)

array([ 7,  5,  7,  8,  4,  7, 11,  7,  9,  1])

In [86]:
np.random.randint(10,40,(10,10)) #generre theelement 10-30 with4*4 mtri

array([[16, 33, 27, 35, 15, 22, 29, 27, 21, 20],
       [16, 21, 12, 10, 23, 36, 35, 12, 16, 14],
       [21, 13, 20, 39, 15, 26, 20, 37, 24, 15],
       [32, 36, 17, 31, 37, 17, 28, 19, 29, 20],
       [36, 33, 37, 27, 26, 28, 20, 16, 22, 30],
       [21, 11, 10, 10, 26, 36, 39, 39, 18, 14],
       [31, 20, 33, 33, 11, 30, 20, 36, 27, 17],
       [26, 14, 36, 14, 22, 23, 25, 28, 13, 35],
       [21, 31, 32, 20, 37, 37, 38, 12, 24, 21],
       [36, 30, 24, 13, 13, 38, 36, 27, 32, 32]])

In [87]:
b = np.random.randint(10,20,(5,4))

In [88]:
b

array([[13, 11, 17, 19],
       [15, 19, 11, 19],
       [10, 18, 19, 19],
       [10, 15, 10, 10],
       [14, 14, 17, 19]])

In [89]:
b[:]

array([[13, 11, 17, 19],
       [15, 19, 11, 19],
       [10, 18, 19, 19],
       [10, 15, 10, 10],
       [14, 14, 17, 19]])

In [90]:
b[0:2]

array([[13, 11, 17, 19],
       [15, 19, 11, 19]])

In [91]:
b

array([[13, 11, 17, 19],
       [15, 19, 11, 19],
       [10, 18, 19, 19],
       [10, 15, 10, 10],
       [14, 14, 17, 19]])

In [92]:
b[0:-1]

array([[13, 11, 17, 19],
       [15, 19, 11, 19],
       [10, 18, 19, 19],
       [10, 15, 10, 10]])

In [93]:
b

array([[13, 11, 17, 19],
       [15, 19, 11, 19],
       [10, 18, 19, 19],
       [10, 15, 10, 10],
       [14, 14, 17, 19]])

In [94]:
b[0,2]

17

In [96]:
np.random.randint(10,20,(4,4))

array([[19, 16, 17, 10],
       [11, 17, 15, 16],
       [14, 15, 11, 18],
       [10, 18, 16, 18]])

operation

In [98]:
a = np.random.randint(10,20,5)

In [99]:
a

array([10, 14, 18, 13, 11])

In [100]:
arr

array([0, 1, 2, 3, 4, 5])

In [103]:
arr2 = np.random.randint(0,100,(10,10))

In [104]:
arr2

array([[83, 86, 15,  1, 23,  8,  8, 49, 86,  6],
       [19, 47, 64, 62, 35, 35, 51, 82, 27, 69],
       [58, 23, 95,  0, 26, 47, 97, 20,  2, 20],
       [ 1, 59, 97, 31, 45, 64, 77, 71, 40, 93],
       [ 3, 29, 22, 54, 35, 65, 78, 63, 79, 26],
       [75, 98, 25, 57, 67, 47, 80, 23, 92, 49],
       [64, 95, 64, 74,  6, 74,  7,  3, 49, 28],
       [67, 96, 84, 28, 42, 15,  9, 35, 79, 96],
       [67, 35, 88, 28,  7, 43, 84, 33, 67, 71],
       [93,  3, 55, 66, 43, 83, 97, 39, 39, 60]])

In [105]:
arr

array([0, 1, 2, 3, 4, 5])

In [106]:
arr

array([0, 1, 2, 3, 4, 5])

In [107]:
arr[:]

array([0, 1, 2, 3, 4, 5])

In [108]:
arr[:4]

array([0, 1, 2, 3])

In [109]:
arr2[:]

array([[83, 86, 15,  1, 23,  8,  8, 49, 86,  6],
       [19, 47, 64, 62, 35, 35, 51, 82, 27, 69],
       [58, 23, 95,  0, 26, 47, 97, 20,  2, 20],
       [ 1, 59, 97, 31, 45, 64, 77, 71, 40, 93],
       [ 3, 29, 22, 54, 35, 65, 78, 63, 79, 26],
       [75, 98, 25, 57, 67, 47, 80, 23, 92, 49],
       [64, 95, 64, 74,  6, 74,  7,  3, 49, 28],
       [67, 96, 84, 28, 42, 15,  9, 35, 79, 96],
       [67, 35, 88, 28,  7, 43, 84, 33, 67, 71],
       [93,  3, 55, 66, 43, 83, 97, 39, 39, 60]])

In [110]:
arr2[0:5]

array([[83, 86, 15,  1, 23,  8,  8, 49, 86,  6],
       [19, 47, 64, 62, 35, 35, 51, 82, 27, 69],
       [58, 23, 95,  0, 26, 47, 97, 20,  2, 20],
       [ 1, 59, 97, 31, 45, 64, 77, 71, 40, 93],
       [ 3, 29, 22, 54, 35, 65, 78, 63, 79, 26]])

In [111]:
arr2

array([[83, 86, 15,  1, 23,  8,  8, 49, 86,  6],
       [19, 47, 64, 62, 35, 35, 51, 82, 27, 69],
       [58, 23, 95,  0, 26, 47, 97, 20,  2, 20],
       [ 1, 59, 97, 31, 45, 64, 77, 71, 40, 93],
       [ 3, 29, 22, 54, 35, 65, 78, 63, 79, 26],
       [75, 98, 25, 57, 67, 47, 80, 23, 92, 49],
       [64, 95, 64, 74,  6, 74,  7,  3, 49, 28],
       [67, 96, 84, 28, 42, 15,  9, 35, 79, 96],
       [67, 35, 88, 28,  7, 43, 84, 33, 67, 71],
       [93,  3, 55, 66, 43, 83, 97, 39, 39, 60]])

In [112]:
arr2[1,5]

35

In [113]:
arr2

array([[83, 86, 15,  1, 23,  8,  8, 49, 86,  6],
       [19, 47, 64, 62, 35, 35, 51, 82, 27, 69],
       [58, 23, 95,  0, 26, 47, 97, 20,  2, 20],
       [ 1, 59, 97, 31, 45, 64, 77, 71, 40, 93],
       [ 3, 29, 22, 54, 35, 65, 78, 63, 79, 26],
       [75, 98, 25, 57, 67, 47, 80, 23, 92, 49],
       [64, 95, 64, 74,  6, 74,  7,  3, 49, 28],
       [67, 96, 84, 28, 42, 15,  9, 35, 79, 96],
       [67, 35, 88, 28,  7, 43, 84, 33, 67, 71],
       [93,  3, 55, 66, 43, 83, 97, 39, 39, 60]])

In [114]:
arr2[-5,5]

47

In [115]:
arr2[-5,-5]

47

In [117]:
arr2

array([[83, 86, 15,  1, 23,  8,  8, 49, 86,  6],
       [19, 47, 64, 62, 35, 35, 51, 82, 27, 69],
       [58, 23, 95,  0, 26, 47, 97, 20,  2, 20],
       [ 1, 59, 97, 31, 45, 64, 77, 71, 40, 93],
       [ 3, 29, 22, 54, 35, 65, 78, 63, 79, 26],
       [75, 98, 25, 57, 67, 47, 80, 23, 92, 49],
       [64, 95, 64, 74,  6, 74,  7,  3, 49, 28],
       [67, 96, 84, 28, 42, 15,  9, 35, 79, 96],
       [67, 35, 88, 28,  7, 43, 84, 33, 67, 71],
       [93,  3, 55, 66, 43, 83, 97, 39, 39, 60]])

In [118]:
arr2[-1,-2]

39

In [119]:
arr2

array([[83, 86, 15,  1, 23,  8,  8, 49, 86,  6],
       [19, 47, 64, 62, 35, 35, 51, 82, 27, 69],
       [58, 23, 95,  0, 26, 47, 97, 20,  2, 20],
       [ 1, 59, 97, 31, 45, 64, 77, 71, 40, 93],
       [ 3, 29, 22, 54, 35, 65, 78, 63, 79, 26],
       [75, 98, 25, 57, 67, 47, 80, 23, 92, 49],
       [64, 95, 64, 74,  6, 74,  7,  3, 49, 28],
       [67, 96, 84, 28, 42, 15,  9, 35, 79, 96],
       [67, 35, 88, 28,  7, 43, 84, 33, 67, 71],
       [93,  3, 55, 66, 43, 83, 97, 39, 39, 60]])

In [120]:
arr2[::-1]

array([[93,  3, 55, 66, 43, 83, 97, 39, 39, 60],
       [67, 35, 88, 28,  7, 43, 84, 33, 67, 71],
       [67, 96, 84, 28, 42, 15,  9, 35, 79, 96],
       [64, 95, 64, 74,  6, 74,  7,  3, 49, 28],
       [75, 98, 25, 57, 67, 47, 80, 23, 92, 49],
       [ 3, 29, 22, 54, 35, 65, 78, 63, 79, 26],
       [ 1, 59, 97, 31, 45, 64, 77, 71, 40, 93],
       [58, 23, 95,  0, 26, 47, 97, 20,  2, 20],
       [19, 47, 64, 62, 35, 35, 51, 82, 27, 69],
       [83, 86, 15,  1, 23,  8,  8, 49, 86,  6]])

In [121]:
arr2

array([[83, 86, 15,  1, 23,  8,  8, 49, 86,  6],
       [19, 47, 64, 62, 35, 35, 51, 82, 27, 69],
       [58, 23, 95,  0, 26, 47, 97, 20,  2, 20],
       [ 1, 59, 97, 31, 45, 64, 77, 71, 40, 93],
       [ 3, 29, 22, 54, 35, 65, 78, 63, 79, 26],
       [75, 98, 25, 57, 67, 47, 80, 23, 92, 49],
       [64, 95, 64, 74,  6, 74,  7,  3, 49, 28],
       [67, 96, 84, 28, 42, 15,  9, 35, 79, 96],
       [67, 35, 88, 28,  7, 43, 84, 33, 67, 71],
       [93,  3, 55, 66, 43, 83, 97, 39, 39, 60]])

In [122]:
arr2

array([[83, 86, 15,  1, 23,  8,  8, 49, 86,  6],
       [19, 47, 64, 62, 35, 35, 51, 82, 27, 69],
       [58, 23, 95,  0, 26, 47, 97, 20,  2, 20],
       [ 1, 59, 97, 31, 45, 64, 77, 71, 40, 93],
       [ 3, 29, 22, 54, 35, 65, 78, 63, 79, 26],
       [75, 98, 25, 57, 67, 47, 80, 23, 92, 49],
       [64, 95, 64, 74,  6, 74,  7,  3, 49, 28],
       [67, 96, 84, 28, 42, 15,  9, 35, 79, 96],
       [67, 35, 88, 28,  7, 43, 84, 33, 67, 71],
       [93,  3, 55, 66, 43, 83, 97, 39, 39, 60]])

In [123]:
arr2[::-2]

array([[93,  3, 55, 66, 43, 83, 97, 39, 39, 60],
       [67, 96, 84, 28, 42, 15,  9, 35, 79, 96],
       [75, 98, 25, 57, 67, 47, 80, 23, 92, 49],
       [ 1, 59, 97, 31, 45, 64, 77, 71, 40, 93],
       [19, 47, 64, 62, 35, 35, 51, 82, 27, 69]])

In [124]:
arr2

array([[83, 86, 15,  1, 23,  8,  8, 49, 86,  6],
       [19, 47, 64, 62, 35, 35, 51, 82, 27, 69],
       [58, 23, 95,  0, 26, 47, 97, 20,  2, 20],
       [ 1, 59, 97, 31, 45, 64, 77, 71, 40, 93],
       [ 3, 29, 22, 54, 35, 65, 78, 63, 79, 26],
       [75, 98, 25, 57, 67, 47, 80, 23, 92, 49],
       [64, 95, 64, 74,  6, 74,  7,  3, 49, 28],
       [67, 96, 84, 28, 42, 15,  9, 35, 79, 96],
       [67, 35, 88, 28,  7, 43, 84, 33, 67, 71],
       [93,  3, 55, 66, 43, 83, 97, 39, 39, 60]])

In [125]:
arr2[::-3]

array([[93,  3, 55, 66, 43, 83, 97, 39, 39, 60],
       [64, 95, 64, 74,  6, 74,  7,  3, 49, 28],
       [ 1, 59, 97, 31, 45, 64, 77, 71, 40, 93],
       [83, 86, 15,  1, 23,  8,  8, 49, 86,  6]])

In [126]:
arr

array([0, 1, 2, 3, 4, 5])

In [127]:
arr.max()

5

In [128]:
arr.min()

0

In [129]:
arr

array([0, 1, 2, 3, 4, 5])

In [130]:
arr.mean()

2.5

In [134]:
arr.median()

AttributeError: 'numpy.ndarray' object has no attribute 'median'

In [136]:
>>> from numpy import*
>>> a= array([1,2,3,4,9,])
>>> median(a)

3.0

In [137]:
arr

array([0, 1, 2, 3, 4, 5])

In [138]:
arr.reshape(2,3)

array([[0, 1, 2],
       [3, 4, 5]])

In [139]:
arr.reshape(6,1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [140]:
arr.reshape(1,6)

array([[0, 1, 2, 3, 4, 5]])

In [141]:
arr.reshape(1,6)

array([[0, 1, 2, 3, 4, 5]])

In [142]:
arr

array([0, 1, 2, 3, 4, 5])

In [143]:
arr.reshape(1,5)

ValueError: cannot reshape array of size 6 into shape (1,5)

In [144]:
arr.reshape(3,2,order='c')

array([[0, 1],
       [2, 3],
       [4, 5]])

In [145]:
arr.reshape(3,2,order='f')

array([[0, 3],
       [1, 4],
       [2, 5]])

In [146]:
arr.reshape(3,2,order='a')

array([[0, 1],
       [2, 3],
       [4, 5]])

In [147]:
arr.reshape(3,2,order='k')

ValueError: order 'K' is not permitted for reshaping

In [148]:
arr

array([0, 1, 2, 3, 4, 5])

In [149]:
arr.reshape(2,3)


array([[0, 1, 2],
       [3, 4, 5]])

In [150]:
arr.reshape(1,4)

ValueError: cannot reshape array of size 6 into shape (1,4)

In [151]:
arr.reshape(1,6)

array([[0, 1, 2, 3, 4, 5]])

In [152]:
arr.reshape(6,1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [153]:
arr.reshape(2,6)

ValueError: cannot reshape array of size 6 into shape (2,6)

In [154]:
arr.reshape(3,3)

ValueError: cannot reshape array of size 6 into shape (3,3)

In [155]:
arr

array([0, 1, 2, 3, 4, 5])

In [156]:
arr.reshape(3,2)

array([[0, 1],
       [2, 3],
       [4, 5]])

Indexing

In [157]:
mat = np.arange(0,100).reshape(10,10)

In [158]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [159]:
rpw = 4
col = 5

In [165]:
col

5

In [167]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [169]:
mat[4,5]

45

In [170]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [171]:
mat[:]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [172]:
col = 6

In [173]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [174]:
mat[:]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [175]:
mat[:,8]

array([ 8, 18, 28, 38, 48, 58, 68, 78, 88, 98])

In [176]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [177]:
mat[:,-1]

array([ 9, 19, 29, 39, 49, 59, 69, 79, 89, 99])

In [178]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [179]:
row

NameError: name 'row' is not defined

In [180]:
col

6

In [181]:
mat[:,col]

array([ 6, 16, 26, 36, 46, 56, 66, 76, 86, 96])

In [182]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [183]:
mat[1,4]

14

In [184]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [185]:
mat[1:4]

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39]])

In [186]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [187]:
mat[3:-3]

array([[30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69]])

In [188]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [189]:
mat[0]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [190]:
mat[6]

array([60, 61, 62, 63, 64, 65, 66, 67, 68, 69])

In [191]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [192]:
mat[6:]

array([[60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [193]:
mat[:6]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [194]:
mat


array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [195]:
mat[5:7]

array([[50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69]])

In [196]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [197]:
mat[0:10]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [198]:
mat[0:10:3]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [199]:
mat[0:10]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [200]:
mat[0:10:3]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [201]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [202]:
mat[4:]

array([[40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [203]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [204]:
mat[:4]


array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39]])

In [205]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [206]:
mat[::-5]

array([[90, 91, 92, 93, 94, 95, 96, 97, 98, 99],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [207]:
mat[2:6]


array([[20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [208]:
mat[1:2,2:4]

array([[12, 13]])

In [209]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [210]:
mat[2:3,2:3]

array([[22]])

In [211]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [212]:
mat[3:5,2:4]

array([[32, 33],
       [42, 43]])

masking

In [213]:
mat #we also called as filter

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [214]:
id(mat)

2000361198416

In [215]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [216]:
mat<50

array([[ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False]])

In [217]:
mat>50

array([[False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True]])

In [218]:
mat ==50

array([[False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [ True, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False]])

In [219]:
mat[mat==50]

array([50])

In [221]:
a1 = mat[mat<50]
a1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [222]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [224]:
a2 = mat[mat>50]
a2

array([51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])